# Generated by Django 5.1.1 on 2024-10-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
