# Generated by Django 5.1.1 on 2024-10-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storage_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
