# Generated by Django 5.1.1 on 2024-11-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_storage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
