# Generated by Django 5.1.1 on 2024-10-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='car_model',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='car_plate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='cellphone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
