# Generated by Django 5.1.1 on 2024-10-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_car_model_alter_client_car_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_store',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
