# Generated by Django 5.1.1 on 2024-10-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_is_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cellphone',
            field=models.CharField(default='(00) 00000-0000', max_length=20),
        ),
    ]
