# Generated by Django 5.1.1 on 2024-11-20 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('service_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services_category', to='service_order.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_cellphone', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_plate', models.CharField(max_length=10)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.CharField(default='', max_length=255)),
                ('paid', models.BooleanField(verbose_name='Payment Made')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=18, null=True)),
                ('service1', models.ManyToManyField(blank=True, default=1, to='service_order.services')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
