# Generated by Django 5.1.1 on 2024-10-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_cellphone', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_plate', models.CharField(max_length=255)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.CharField(max_length=255)),
                ('paid', models.BooleanField(verbose_name='Payment Made')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
