# Generated by Django 5.1.1 on 2024-10-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0003_alter_serviceorder_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='client_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='car_plate',
            field=models.CharField(max_length=10),
        ),
    ]
