# Generated by Django 5.1.1 on 2024-10-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0004_serviceorder_client_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='client_address',
        ),
    ]
