# Generated by Django 5.1.1 on 2024-10-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0005_remove_serviceorder_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
