# Generated by Django 5.1.1 on 2024-10-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0009_alter_serviceorder_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='car_plate',
            field=models.CharField(max_length=18),
        ),
    ]
