# Generated by Django 5.1.1 on 2024-10-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0015_alter_serviceorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
