# Generated by Django 5.1.1 on 2024-10-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0017_service_remove_serviceorder_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='service1',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='service_order', to='service_order.service'),
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='service',
            field=models.CharField(default='', max_length=255),
        ),
    ]
