# Generated by Django 5.1.1 on 2024-10-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0018_serviceorder_service1_remove_serviceorder_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service1',
            field=models.ManyToManyField(blank=True, related_name='service_order', to='service_order.service'),
        ),
    ]
