# Generated by Django 5.1.1 on 2024-10-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0019_service_category_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='service',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
