# Generated by Django 5.1.1 on 2024-10-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0020_alter_serviceorder_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='service1',
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
