# Generated by Django 5.1.1 on 2024-10-24 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0021_servicecategory_remove_serviceorder_service1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('service_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_order.servicecategory')),
            ],
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='service1',
            field=models.ManyToManyField(blank=True, default=1, to='service_order.services'),
        ),
    ]
