# Generated by Django 5.1.1 on 2024-10-24 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0022_services_serviceorder_service1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_order.servicecategory'),
        ),
    ]
